### PR TITLE
[1.44.2.x-prod][SRVLOGIC-185] Change builder configMap default name

### PR DESCRIPTION
**Pull request by ricardozanini**
**Description of the change:**
Change to reflect productized names in the codebase.

**Motivation for the change:**
See https://issues.redhat.com/browse/SRVLOGIC-185

**Checklist**

- [ ] Add or Modify a unit test for your change
- [ ] Have you verified that tall the tests are passing?

<details>
<summary>
How to backport a pull request to a different branch?
</summary>

In order to automatically create a **backporting pull request** please add one or more labels having the following format `backport-<branch-name>`, where `<branch-name>` is the name of the branch where the pull request must be backported to (e.g., `backport-7.67.x` to backport the original PR to the `7.67.x` branch).

> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still maintained release branch. Keeping it simple: it is about to move a specific change or a set of them from one branch to another.

Once the original pull request is successfully merged, the automated action will create one backporting pull request per each label (with the previous format) that has been added.

If something goes wrong, the author will be notified and at this point a manual backporting is needed.

> **NOTE**: this automated backporting is triggered whenever a pull request on `main` branch is labeled or closed, but both conditions must be satisfied to get the new PR created.
</details>

### CODE REVIEW

**Review by jakubschwan — APPROVED** [review]

**Review by rgdoliveira — APPROVED** [review]

**Comment by ricardozanini** [comment]
e2e is failing with:

```
Error: error creating build container: initializing source docker://registry.access.redhat.com/ubi8/ubi-micro:latest: reading manifest latest in registry.access.redhat.com/ubi8/ubi-micro: received unexpected HTTP status: 502 Bad Gateway
2023-11-29 15:03:49,131 tools.py:366        ERROR Command '['/usr/bin/podman', 'build', '--squash', '-t', 'kogito-serverless-operator:2.0.0-snapshot', '-t', 'kogito-serverless-operator:latest', 'target/image']' returned non-zero exit status 125. Command stdout is 'None' with stderr 'None'
2023-11-29 15:03:49,132 cli.py:500        ERROR ("Could not run podman ['/usr/bin/podman', 'build', '--squash', '-t', 'kogito-serverless-operator:2.0.0-snapshot', '-t', 'kogito-serverless-operator:latest', 'target/image']", CalledProcessError(125, ['/usr/bin/podman', 'build', '--squash', '-t', 'kogito-serverless-operator:2.0.0-snapshot', '-t', 'kogito-serverless-operator:latest', 'target/image']))
```

👀

**Review by jakubschwan — APPROVED** [review]

**Comment by ricardozanini** [comment]
@jakubschwan @domhanak have you verified?

**Comment by domhanak** [comment]
@ricardozanini Jakub approved so I guess it is verified.

What about the failing E2E?

**Comment by jakubschwan** [comment]
changes looks good to me. Now testing it with fixes for KOGITO-9729

**Comment by ricardozanini** [comment]
> @ricardozanini Jakub approved so I guess it is verified.
> 
> What about the failing E2E?

@domhanak it's failing because we've changed the CM builder name, and the minikube is deploying the old one.

**Review by domhanak — APPROVED** [review]

**Pull request merged**
