### PR TITLE
[1.44.2.x] - Critical bugs and CVEs cherry-picks

### PR DESCRIPTION
**Pull request by ricardozanini**
**Description of the change:**

**Motivation for the change:**

**Checklist**

- [ ] Add or Modify a unit test for your change
- [ ] Have you verified that tall the tests are passing?

<details>
<summary>
How to backport a pull request to a different branch?
</summary>

In order to automatically create a **backporting pull request** please add one or more labels having the following format `backport-<branch-name>`, where `<branch-name>` is the name of the branch where the pull request must be backported to (e.g., `backport-7.67.x` to backport the original PR to the `7.67.x` branch).

> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still maintained release branch. Keeping it simple: it is about to move a specific change or a set of them from one branch to another.

Once the original pull request is successfully merged, the automated action will create one backporting pull request per each label (with the previous format) that has been added.

If something goes wrong, the author will be notified and at this point a manual backporting is needed.

> **NOTE**: this automated backporting is triggered whenever a pull request on `main` branch is labeled or closed, but both conditions must be satisfied to get the new PR created.
</details>

### CODE REVIEW

**Comment by ricardozanini** [comment]
@rgdoliveira I think the Jenkins CI error is unrelated:

```
org.kie.jenkins.jobdsl.JobScriptsSpec > test script /tmp/tmp.SUYP1HA3PZ/dsl/seed/jobs/jobs.groovy FAILED
    org.spockframework.runtime.UnallowedExceptionThrownError at JobScriptsSpec.groovy:76
        Caused by: javaposse.jobdsl.dsl.DslScriptException at JobScriptsSpec.groovy:72
            Caused by: groovy.lang.MissingMethodException at JobScriptsSpec.groovy:72
```

**Review by rgdoliveira — APPROVED** [review]

**Comment by domhanak** [comment]
@rgdoliveira @ricardozanini what about the failed **Jenkins Tests / dsl-tests** ?

**Comment by ricardozanini** [comment]
@domhanak please see my last comment. It seems to me infrastructure-related. Our IT is working as expected.

**Review by jakubschwan — APPROVED** [review]
lgtm

**Review by domhanak — APPROVED** [review]

**Pull request merged**
